# Generated by Django 4.1.4 on 2022-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres del autor')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del autor')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='twitter')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('web', models.URLField(verbose_name='web')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del autor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del autor')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la categoría')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
