# Generated by Django 4.1.4 on 2023-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['titulo'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
